name: Go

on:
  push:
    branches: [ main, release-* ]
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish
      run:  |
        docker login quay.io/gurnbenibm/cm:latest && \
        docker build . -t quay.io/gurnbenibm/cm:latest && \
        docker push quay.io/gurnbenibm/cm:latest
