name: Build

on:
  push:
    branches: [ main, release-* ]
  schedule:
    - cron:  '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:  |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io/gurnbenibm/cm:latest && \
        docker build . -t quay.io/gurnbenibm/cm:latest && \
        docker push quay.io/gurnbenibm/cm:latest
